-- SentinelAI :: security_events (event module)
CREATE TABLE security_events (
    id                BIGINT                                                                                                 NOT NULL AUTO_INCREMENT,
    org_id            BIGINT                                                                                                 NOT NULL,
    event_type        ENUM('FAILED_LOGIN', 'BRUTE_FORCE', 'SUSPICIOUS_LOGIN', 'API_ABUSE', 'ABNORMAL_ACCESS', 'HONEYTOKEN_ACCESS', 'OTHER') NOT NULL,
    severity          ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')                                                              NOT NULL,
    source_ip         VARCHAR(45)                                                                                            NULL,
    username          VARCHAR(100)                                                                                           NULL,
    user_agent        VARCHAR(512)                                                                                           NULL,
    resource          VARCHAR(255)                                                                                           NULL,
    asset_criticality TINYINT                                                                                                NULL,
    raw_payload       JSON                                                                                                   NULL,
    geo_country       VARCHAR(2)                                                                                             NULL,
    geo_city          VARCHAR(100)                                                                                           NULL,
    is_honeytoken     TINYINT(1)                                                                                             NOT NULL DEFAULT 0,
    entity_key        VARCHAR(255)                                                                                           NULL,
    correlation_key   VARCHAR(255)                                                                                           NULL,
    event_timestamp   DATETIME(6)                                                                                            NOT NULL,
    ingested_at       DATETIME(6)                                                                                            NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_events_timestamp (event_timestamp),
    KEY idx_events_source_ip (source_ip),
    KEY idx_events_severity (severity),
    KEY idx_events_type (event_type),
    KEY idx_events_username (username),
    KEY idx_events_entity_key (entity_key),
    KEY idx_events_correlation_key (correlation_key),
    KEY idx_events_org_timestamp (org_id, event_timestamp),
    CONSTRAINT fk_events_org FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
