package com.sentinelai.demo;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import lombok.Getter;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.validation.annotation.Validated;

/**
 * Demo Center configuration. Off by default; the {@code demo} (and {@code dev}) profile turns it on.
 * {@code quickLogin} additionally exposes the seeded demo accounts on the login page — never enable
 * it on an instance with real users.
 */
@Getter
@Setter
@Validated
@ConfigurationProperties(prefix = "sentinel.demo")
public class DemoProperties {

    private boolean enabled = false;

    private boolean quickLogin = false;

    /** Benign + malicious events generated by "Seed sample data" across the last 24 hours. */
    @Min(10)
    @Max(2000)
    private int baselineEvents = 240;

    /** Hard cap on events a single scenario run may ingest. */
    @Min(10)
    @Max(5000)
    private int maxEventsPerRun = 500;
}
